name: EB-Modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=5.1
  - astroquery=0.4.5
  - emcee=3.1.1
  - matplotlib=3.5.2
  - numpy=1.21.6
  - PHOEBE=2.4.14
  - python=3.11
  - scikit-learn=1.1.1
  - scipy=1.7.3

